#pragma config(UART_Usage, UART2, uartUserControl, baudRate9600, IOPins, None, None)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                   VEX
//
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

task UARTReceive();

int rcvChar;

task main()
{
	// Setup the two UART ports
	setBaudRate(uartTwo, baudRate9600);

	while (getChar(uartTwo) != -1) // Purge existing chars from buffer
	{}

	startTask(UARTReceive);

}


task UARTReceive()
{
	while (true)
	{
		// Loop forever getting characters from the "receive" UART. Validate that they arrive in the expected
		// sequence.

		rcvChar = getChar(uartTwo);
		if (rcvChar == -1)
		{
			// No character available

			wait1Msec(2); // Don't want to consume too much CPU time. Waiting eliminates CPU consumption for this task.
			continue;
		}
		waitInMilliseconds(1000);
	}
}
